-- PostgreSQL 17 + pgvector – N8N Automation Platform 2026
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "vector";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "citext";

CREATE TABLE organizations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, plan TEXT DEFAULT 'starter', settings JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE tenants (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE, name TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID REFERENCES organizations(id), email CITEXT UNIQUE NOT NULL, password_hash TEXT, full_name TEXT, mfa_secret TEXT, mfa_enabled BOOLEAN DEFAULT false, status TEXT DEFAULT 'active', created_at TIMESTAMPTZ DEFAULT now(), last_login_at TIMESTAMPTZ);
CREATE TABLE roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE, name TEXT NOT NULL, permissions JSONB DEFAULT '[]'::jsonb, UNIQUE(organization_id, name));
CREATE TABLE user_roles (user_id UUID REFERENCES users(id) ON DELETE CASCADE, role_id UUID REFERENCES roles(id) ON DELETE CASCADE, tenant_id UUID REFERENCES tenants(id), PRIMARY KEY (user_id, role_id, tenant_id));
CREATE TABLE teams (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID REFERENCES organizations(id), tenant_id UUID REFERENCES tenants(id), name TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE api_keys (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), tenant_id UUID REFERENCES tenants(id), name TEXT NOT NULL, key_hash TEXT NOT NULL, scopes TEXT[] DEFAULT ARRAY[]::TEXT[], last_used_at TIMESTAMPTZ, expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE workflows (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), tenant_id UUID REFERENCES tenants(id), name TEXT NOT NULL, slug TEXT NOT NULL, description TEXT, n8n_workflow_id TEXT, tags TEXT[], is_active BOOLEAN DEFAULT true, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(organization_id, slug));
CREATE TABLE workflow_versions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id UUID NOT NULL REFERENCES workflows(id) ON DELETE CASCADE, version INT NOT NULL, definition JSONB NOT NULL, created_by UUID REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT now(), UNIQUE(workflow_id, version));
CREATE TABLE workflow_runs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workflow_id UUID NOT NULL REFERENCES workflows(id), organization_id UUID NOT NULL REFERENCES organizations(id), tenant_id UUID REFERENCES tenants(id), status TEXT NOT NULL, trigger TEXT, started_at TIMESTAMPTZ DEFAULT now(), finished_at TIMESTAMPTZ, duration_ms INT, error TEXT) PARTITION BY RANGE (started_at);
CREATE TABLE workflow_runs_2026_01 PARTITION OF workflow_runs FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE workflow_runs_2026_02 PARTITION OF workflow_runs FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE workflow_runs_2026_03 PARTITION OF workflow_runs FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');
CREATE TABLE workflow_logs (id BIGSERIAL PRIMARY KEY, run_id UUID NOT NULL, level TEXT, message TEXT, meta JSONB, ts TIMESTAMPTZ DEFAULT now()) PARTITION BY RANGE (ts);
CREATE TABLE workflow_logs_2026_01 PARTITION OF workflow_logs FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE integrations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), name TEXT NOT NULL, provider TEXT NOT NULL, credentials JSONB, status TEXT DEFAULT 'active', created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE webhooks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), tenant_id UUID REFERENCES tenants(id), workflow_id UUID REFERENCES workflows(id), secret TEXT NOT NULL, url_path TEXT UNIQUE NOT NULL, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE ai_agents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), tenant_id UUID REFERENCES tenants(id), name TEXT NOT NULL, type TEXT NOT NULL, model TEXT DEFAULT 'gpt-4o', system_prompt TEXT NOT NULL, tools JSONB DEFAULT '[]'::jsonb, mcp_servers JSONB DEFAULT '[]'::jsonb, memory_window INT DEFAULT 20, is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE ai_conversations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), agent_id UUID REFERENCES ai_agents(id), organization_id UUID NOT NULL REFERENCES organizations(id), user_id UUID REFERENCES users(id), external_id TEXT, meta JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE ai_messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id UUID REFERENCES ai_conversations(id) ON DELETE CASCADE, role TEXT NOT NULL, content TEXT NOT NULL, tokens INT, tool_calls JSONB, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE vector_documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), tenant_id UUID REFERENCES tenants(id), source TEXT, title TEXT, content TEXT NOT NULL, metadata JSONB DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE embeddings (document_id UUID REFERENCES vector_documents(id) ON DELETE CASCADE, chunk_index INT, content TEXT NOT NULL, embedding vector(1536), PRIMARY KEY (document_id, chunk_index));
CREATE INDEX ON embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE TABLE notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), user_id UUID REFERENCES users(id), channel TEXT NOT NULL, title TEXT NOT NULL, body TEXT, read_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE audit_logs (id BIGSERIAL PRIMARY KEY, organization_id UUID, actor_id UUID, action TEXT NOT NULL, target_type TEXT, target_id TEXT, ip INET, meta JSONB, created_at TIMESTAMPTZ DEFAULT now()) PARTITION BY RANGE (created_at);
CREATE TABLE audit_logs_2026_01 PARTITION OF audit_logs FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE subscriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), plan TEXT NOT NULL, status TEXT NOT NULL, seats INT DEFAULT 5, executions_quota INT DEFAULT 100000, current_period_start DATE, current_period_end DATE, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE invoices (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID NOT NULL REFERENCES organizations(id), subscription_id UUID REFERENCES subscriptions(id), amount_cents INT NOT NULL, currency TEXT DEFAULT 'usd', status TEXT DEFAULT 'pending', issued_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE settings (organization_id UUID PRIMARY KEY REFERENCES organizations(id), data JSONB DEFAULT '{}'::jsonb, updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE system_metrics (ts TIMESTAMPTZ DEFAULT now(), metric TEXT NOT NULL, organization_id UUID, value DOUBLE PRECISION, labels JSONB, PRIMARY KEY (ts, metric));
ALTER TABLE workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE vector_documents ENABLE ROW LEVEL SECURITY;
CREATE OR REPLACE FUNCTION current_org() RETURNS UUID LANGUAGE sql STABLE AS $$ SELECT NULLIF(current_setting('app.current_org', true), '')::UUID $$;
CREATE POLICY tenant_isolation_workflows ON workflows USING (organization_id = current_org());
CREATE POLICY tenant_isolation_agents ON ai_agents USING (organization_id = current_org());
CREATE POLICY tenant_isolation_docs ON vector_documents USING (organization_id = current_org());
CREATE INDEX ON workflows(organization_id, is_active);
CREATE INDEX ON workflow_runs(workflow_id, started_at DESC);
CREATE INDEX ON ai_messages(conversation_id, created_at);
CREATE INDEX ON audit_logs(organization_id, created_at DESC);
CREATE VIEW workflow_analytics AS SELECT organization_id, workflow_id, date_trunc('day', started_at) as day, count(*) as runs, avg(duration_ms) as avg_ms, sum(CASE WHEN status='success' THEN 1 ELSE 0 END)::float / NULLIF(count(*),0) as success_rate FROM workflow_runs GROUP BY 1,2,3;
CREATE MATERIALIZED VIEW mv_agent_usage_daily AS SELECT agent_id, date_trunc('day', created_at) as day, count(*) as messages, sum(tokens) as tokens FROM ai_messages m JOIN ai_conversations c ON c.id=m.conversation_id GROUP BY 1,2 WITH NO DATA;
